# Site settings
title: StephenOrr.co.uk
email: steve@stephenorr.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website of Stephen Orr, containing blog
  posts about cool technologies, Ruby, PHP, JavaScript and the
  occasional game development post.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.stephenorr.co.uk" # the base hostname & protocol for your site
twitter_username: StephenOrr1981
github_username:  stephenorr

# Build settings
markdown: kramdown

# Collections
collections:
  projects:
    output: true
